name: rss_feed_reader
description: A RSS Reader built by Flutter

publish_to: "none"

version: 3.0.0+11

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  cached_network_image:
  collection:
  # crypto:
  # desktop_window:
  dio:
  drift:
  flutter:
    sdk: flutter
  flutter_colorpicker:
  flutter_html:
  flutter_linkify:
  flutter_riverpod:
  html_unescape:
  # http:
  logging:
  # moor: ^4.6.0
  news_common:
    path: ../news_common
  package_info_plus:
  path:
  path_provider:
  resizable_widget:
  shared_preferences:
  sqlite3_flutter_libs:
  url_launcher:
  win32: #^2.7.0
  window_manager: #^0.2.3
  xml: #^6.1.0
dev_dependencies:
  analyzer: ^6.3.0
  build_runner: #^2.1.11
  drift_dev:
  # dart_style: ^2.2.3
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  # moor_generator: ^4.6.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/twitter.png
    - assets/sounds/twitter.wav
    - assets/sounds/article.wav
flutter_launcher_icons:
  image_path: "assets/launcher_icon/app_icon.png"
  windows:
    generate: true
