name: rss_feed_reader
description: A RSS Reader built by Flutter

publish_to: "none"

version: 1.2.0+5

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  cached_network_image:
  collection:
  crypto:
  desktop_window:
  dio:
  flutter:
    sdk: flutter
  flutter_colorpicker:
  flutter_html:
  flutter_linkify:
  flutter_riverpod:
  html_unescape:
  http:
  logging:
  moor: ^4.0.0
  news_common:
    path: ../news_common
  package_info_plus:
  path:
  path_provider:
  shared_preferences:
  sqlite3_flutter_libs:
  url_launcher:
  win32:
  xml:
dev_dependencies:
  build_runner:
  dart_style: 
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/twitter.png
    - assets/sounds/twitter.wav
    - assets/sounds/article.wav
flutter_icons:
  image_path: "assets/launcher_icon/app_icon.png"
  window: true
  android: true
