name: rss_feed_reader
description: A RSS Reader built by Flutter

publish_to: "none"

version: 1.1.0+4

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  cached_network_image: ^3.0.0
  collection:
  crypto: ^3.0.1
  desktop_window:
  dio:
  flutter:
    sdk: flutter
  flutter_colorpicker:
  flutter_html: ^2.0.0-nullsafety.0
  flutter_linkify: ^5.0.2
  flutter_riverpod:
  html_unescape:
  http: ^0.13.3
  lint: ^1.5.3
  logging: ^1.0.1
  moor: ^4.3.2
  news_common:
    path: ../news_common
  package_info_plus: ^1.0.1
  path:
  path_provider: ^2.0.1
  # pedantic: ^1.11.0
  shared_preferences: ^2.0.12
  sqlite3_flutter_libs: ^0.5.0
  url_launcher:
  win32: ^2.0.5
  xml: ^5.0.2
dev_dependencies:
  build_runner: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  moor_generator: ^4.3.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/twitter.png
    - assets/sounds/twitter.wav
    - assets/sounds/article.wav
flutter_icons:
  image_path: "assets/launcher_icon/app_icon.png"
  window: true
  android: true
