name: news_client_application
description: News client application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cached_network_image:
  flutter:
    sdk: flutter
  flutter_html:
  flutter_linkify:
  flutter_riverpod:
  news_common:
    path: ../news_common
  shared_preferences:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
