name: news_client_application
description: News client application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+7

environment:
  sdk: ^3.7.0-323.2.beta
#  sdk: ">=2.18.0 <4.0.0"

dependencies:
  cached_network_image:
  flutter:
    sdk: flutter
  flutter_html:
  flutter_linkify:
  flutter_riverpod:
  news_common:
    path: ../news_common
  package_info_plus: ^9.0.0
  shared_preferences:
  url_launcher:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  icons_launcher:

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true

flutter:
  uses-material-design: true
